app:
  name: 'glo-profile-service'
  port: '80'
  version: '1.0'
  mobile-version: '1.0.2'

log:
  env: 'dev'
  level: 'debug'

cloud-sql:
  dbname: "lotto"
  gormhost: "(35.247.187.21:3306)"
  username: 'lotto'
  password: 'P@ssw0rd'
  max-idle-conns: 100
  max-open-conns: 100
  max-life-time-minutes: 5

redis:
  host : "localhost"
  port: "6379"
  password: ""
  database: "0"
  poolMaxIdle : 8
  poolMaxActive: 16

aesgcm:
  key1: "Mf65J46OFeNKCIYWTVjG8Fo61vHcYMqY"

jwt:
  key1: "goerm6mvkid6"